### Theoretical Questions:

In [1]:
#Reversing a 1D Array
import numpy as np

# Create a 1D array
arr_1d = np.array([1, 2, 3, 4, 5])

# Reverse the array
reversed_arr_1d = arr_1d[::-1]

print("Original 1D Array:", arr_1d)
print("Reversed 1D Array:", reversed_arr_1d)


Original 1D Array: [1 2 3 4 5]
Reversed 1D Array: [5 4 3 2 1]


In [2]:
#Reversing a 2D Array
# Create a 2D array
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# Reverse the array along axis 0
reversed_arr_2d_axis0 = arr_2d[::-1, :]

print("Original 2D Array:\n", arr_2d)
print("Reversed 2D Array along Axis 0:\n", reversed_arr_2d_axis0)


Original 2D Array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Reversed 2D Array along Axis 0:
 [[7 8 9]
 [4 5 6]
 [1 2 3]]


In [4]:
# example of hstack()
# Create two 2D arrays
array1 = np.array([[1, 2],
                   [3, 4]])

array2 = np.array([[5, 6],
                   [7, 8]])

# Use hstack to stack the arrays horizontally
hstack_result = np.hstack((array1, array2))

print("Array 1:\n", array1)
print("Array 2:\n", array2)
print("hstack Result:\n", hstack_result)


Array 1:
 [[1 2]
 [3 4]]
Array 2:
 [[5 6]
 [7 8]]
hstack Result:
 [[1 2 5 6]
 [3 4 7 8]]


In [5]:
# example of vstack()
import numpy as np

# Create two 2D arrays
array1 = np.array([[1, 2, 3],
                   [4, 5, 6]])

array2 = np.array([[7, 8, 9],
                   [10, 11, 12]])

# Use vstack to stack the arrays vertically
vstack_result = np.vstack((array1, array2))

print("Array 1:\n", array1)
print("Array 2:\n", array2)
print("vstack Result:\n", vstack_result)


Array 1:
 [[1 2 3]
 [4 5 6]]
Array 2:
 [[ 7  8  9]
 [10 11 12]]
vstack Result:
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


### Practical Questions:

In [6]:
import numpy as np

# Create a 3x3 array with random integers between 1 and 100
array_3x3 = np.random.randint(1, 101, size=(3, 3))

print("Original Array:\n", array_3x3)

# Interchange rows and columns (transpose the array)
transposed_array = np.transpose(array_3x3)

print("Transposed Array:\n", transposed_array)


Original Array:
 [[40 31 92]
 [38 90 88]
 [48 56  6]]
Transposed Array:
 [[40 38 48]
 [31 90 56]
 [92 88  6]]


In [7]:
import numpy as np

# Generate a 1D NumPy array with 10 elements
array_1d = np.arange(10)

print("Original 1D Array:\n", array_1d)

# Reshape into a 2x5 array
array_2x5 = array_1d.reshape(2, 5)
print("\nReshaped to 2x5 Array:\n", array_2x5)

# Reshape into a 5x2 array
array_5x2 = array_1d.reshape(5, 2)
print("\nReshaped to 5x2 Array:\n", array_5x2)


Original 1D Array:
 [0 1 2 3 4 5 6 7 8 9]

Reshaped to 2x5 Array:
 [[0 1 2 3 4]
 [5 6 7 8 9]]

Reshaped to 5x2 Array:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [8]:
import numpy as np

# Create a 4x4 array with random float values
array_4x4 = np.random.rand(4, 4)

print("Original 4x4 Array:\n", array_4x4)

# Add a border of zeros around the array
array_with_border = np.pad(array_4x4, pad_width=1, mode='constant', constant_values=0)

print("\n6x6 Array with Border of Zeros:\n", array_with_border)


Original 4x4 Array:
 [[0.30951105 0.86675317 0.90451269 0.62130739]
 [0.67478269 0.4965748  0.76365611 0.49060703]
 [0.41715964 0.01824656 0.38382128 0.35884263]
 [0.81194757 0.29449487 0.59900188 0.07330882]]

6x6 Array with Border of Zeros:
 [[0.         0.         0.         0.         0.         0.        ]
 [0.         0.30951105 0.86675317 0.90451269 0.62130739 0.        ]
 [0.         0.67478269 0.4965748  0.76365611 0.49060703 0.        ]
 [0.         0.41715964 0.01824656 0.38382128 0.35884263 0.        ]
 [0.         0.81194757 0.29449487 0.59900188 0.07330882 0.        ]
 [0.         0.         0.         0.         0.         0.        ]]


In [9]:
import numpy as np

# Create an array of integers from 10 to 60 with a step of 5
array_integers = np.arange(10, 61, 5)

print("Array of integers from 10 to 60 with a step of 5:\n", array_integers)


Array of integers from 10 to 60 with a step of 5:
 [10 15 20 25 30 35 40 45 50 55 60]


In [10]:
import numpy as np

# Create a NumPy array of strings
string_array = np.array(['python', 'numpy', 'pandas'])

# Apply different case transformations
uppercase_array = np.char.upper(string_array)
lowercase_array = np.char.lower(string_array)
titlecase_array = np.char.title(string_array)

# Print the results
print("Original Array:\n", string_array)
print("\nUppercase Transformation:\n", uppercase_array)
print("\nLowercase Transformation:\n", lowercase_array)
print("\nTitle Case Transformation:\n", titlecase_array)


Original Array:
 ['python' 'numpy' 'pandas']

Uppercase Transformation:
 ['PYTHON' 'NUMPY' 'PANDAS']

Lowercase Transformation:
 ['python' 'numpy' 'pandas']

Title Case Transformation:
 ['Python' 'Numpy' 'Pandas']


In [11]:
import numpy as np

# Create a NumPy array of words
words_array = np.array(['python', 'numpy', 'pandas'])

# Insert a space between each character of every word
spaced_words = np.char.join(' ', words_array)

# Print the results
print("Original Array:\n", words_array)
print("\nWords with Spaces Between Characters:\n", spaced_words)


Original Array:
 ['python' 'numpy' 'pandas']

Words with Spaces Between Characters:
 ['p y t h o n' 'n u m p y' 'p a n d a s']


In [12]:
import numpy as np

# Create two 2D NumPy arrays
array1 = np.array([[1, 2, 3],
                   [4, 5, 6]])

array2 = np.array([[7, 8, 9],
                   [10, 11, 12]])

# Perform element-wise operations
addition = array1 + array2
subtraction = array1 - array2
multiplication = array1 * array2
division = array1 / array2

# Print the results
print("Array 1:\n", array1)
print("Array 2:\n", array2)
print("\nElement-wise Addition:\n", addition)
print("\nElement-wise Subtraction:\n", subtraction)
print("\nElement-wise Multiplication:\n", multiplication)
print("\nElement-wise Division:\n", division)


Array 1:
 [[1 2 3]
 [4 5 6]]
Array 2:
 [[ 7  8  9]
 [10 11 12]]

Element-wise Addition:
 [[ 8 10 12]
 [14 16 18]]

Element-wise Subtraction:
 [[-6 -6 -6]
 [-6 -6 -6]]

Element-wise Multiplication:
 [[ 7 16 27]
 [40 55 72]]

Element-wise Division:
 [[0.14285714 0.25       0.33333333]
 [0.4        0.45454545 0.5       ]]


In [13]:
import numpy as np

# Create a 5x5 identity matrix
identity_matrix = np.eye(5)

print("5x5 Identity Matrix:\n", identity_matrix)

# Extract the diagonal elements
diagonal_elements = np.diagonal(identity_matrix)

print("\nDiagonal Elements:\n", diagonal_elements)


5x5 Identity Matrix:
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]

Diagonal Elements:
 [1. 1. 1. 1. 1.]


In [14]:
import numpy as np

# Generate a NumPy array of 100 random integers between 0 and 1000
random_integers = np.random.randint(0, 1000, size=100)

# Function to check if a number is prime
def is_prime(n):
    if n <= 1:
        return False
    for i in range(2, int(n**0.5) + 1):
        if n % i == 0:
            return False
    return True

# Find all prime numbers in the array
prime_numbers = [num for num in random_integers if is_prime(num)]

# Print the results
print("Random Integers:\n", random_integers)
print("\nPrime Numbers:\n", prime_numbers)


Random Integers:
 [882 219 773 394 725   6 947 826 942 366 487 863 517 794  57 226 234 842
 491 776 580  84 539 643 848 227 675  32  51 225 745 394 271 338 649 927
 645 650 596 855 381 872 842 614 794 274 860 375  41 638 819 132 674 925
 396 874  33  29 713 376 381 253 565 507  47 924  94 517 886 140 307 223
 964 332 201 486 449  60 295  14 257 958 948 265  69 388 440 417 312 372
 969 676 385 785 595 590 472 824 680 804]

Prime Numbers:
 [773, 947, 487, 863, 491, 643, 227, 271, 41, 29, 47, 307, 223, 449, 257]
